# Generated by Django 5.1.1 on 2024-10-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_alter_carmodel_model_alter_carmodel_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="carmodel",
            name="photo",
            field=models.ImageField(blank=True, upload_to="storage"),
        ),
    ]
