# Generated by Django 5.1.1 on 2024-10-06 18:29

import django.db.models.deletion
from django.db import migrations, models

import apps.cars.services


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0005_carmodel_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carmodel",
            name="photo",
        ),
        migrations.CreateModel(
            name="CarPhotoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),

                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to=apps.cars.services.upload_car_photo
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="cars.carmodel",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "car_photos",
            },
        ),
    ]
